### ISSUE TITLE
Scrobble

### ISSUE THREAD

**Issue by deluan** [peguerosdc/subplayer#15]
Hey, this is an awesome *Sonic client! Nice job!

I'm working on a new streaming server compatible with subsonic API, [Navidrome](https://github.com/deluan/navidrome).

Your player works perfectly with my server, but one thing I see is missing is the scrobble call, used to increment play counts and update Last.FM Do you have any plans to implement this? 

I'd love to contribute with a PR, but right now I have tons to work on my server...

**Comment by peguerosdc** [comment]
Thanks! I am glad you find it useful :smile: 

I don't have any plans at the moment to implement it, but it would be a nice contribution if you have the time. In the mean time, I will mark it as an enhancement and hopefully I can make time for it in the future.

**Comment by deluan** [comment]
I'd love to contribute to this project, but right now all spare time I have I dedicate to getting Navidrome to version 1.0.

**Comment by deluan** [comment]
Hey, thanks for this! Just one note. Looks like you need to send the `submit=true` scrobble at 50% of the song, and not send any submit if the song is less then 40 seconds: https://github.com/deluan/navidrome/issues/18#issuecomment-656977060

As it is right now, it is not much different from most players out there, though. Even Navidrome dos it wrong (for now): It sends the submit at 90%

Anyway, thanks!

**Comment by peguerosdc** [comment]
I wasn't aware of this "official" definition/recommendation haha thanks! I will fix it and merge to master before pushing this last version to Docker.
