### ISSUE TITLE
[Feature request]: All songs?

### ISSUE THREAD

**Issue by piraterx** [peguerosdc/subplayer#45]
Looks so good but is there a way to make all songs available as tab and we can see all songs rather than only few options. Thank you for this.

**Comment by peguerosdc** [comment]
Hi! Thanks for stopping by!

Unfortunately, the Subsonic API doesn't provide a way to query a list of all available songs.

You could fork the project and implement that view for a specific server implementation if it provides an endpoint (i.e. Navidrome does), but that's not part of what I want as an universal Subsonic music player. Sorry!

**Comment by piraterx** [comment]
> 
> 
> Hi! Thanks for stopping by!
> 
> Unfortunately, the Subsonic API doesn't provide a way to query a list of all available songs.
> 
> You could fork the project and implement that view for a specific server implementation if it provides an endpoint (i.e. Navidrome does), but that's not part of what I want as an universal Subsonic music player. Sorry!

Thank you. I am don't know code but I understand limitation.
